### PR TITLE
Attempt to fix random CORBA timeouts

### LINKED ISSUE #19: Random TimeoutExceptions in java client (TangORB)
In our case we have Java client and a server. Client polls server for a command every 10 ms in a loop. Sometimes this can run smoothly for up to 3 hours, sometimes only 15 minutes. But normally client crashes after ~1h with a timeout exception. We tried with TangORB-8.4.2 and 9.0.1 (both from the soleil's maven repo). Below is some additional information. Suggested workaround patch is attached.

>
> In my test case server is running on debian 7:
>
> Linux hzgpp07ctrec2 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux
> 
> Java version:
> 
> java version "1.8.0_25"
> Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
> Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
> 
> in a server mode, i.e. was launched with -server java param.
> 
> Client is on Windows 7 with java version:
> 
> java version "1.8.0_05"
> Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
> 

Here is some log output:

> [main] INFO org.jacorb.orb - Initialising ORB with ID:
> [main] INFO org.jacorb.orb.giop - ClientConnectionManager: created new  ClientGIOPConnection to 131.169.65.104:10000 (6b927fb)
> [main] INFO org.jacorb.orb.iiop.ClientIIOPConnection - Connected to 131.169.65.104:10000 from local port 56378
> [main] INFO org.jacorb.orb.giop - ClientConnectionManager: created new ClientGIOPConnection to 131.169.65.240:39478 (477b4cdf)
> [main] INFO org.jacorb.orb.iiop.ClientIIOPConnection - Connected to 131.169.65.240:39478 from local port 56379
> [ClientMessageReceptor0] INFO org.jacorb.giop.conn - Received CloseConnection on ClientGIOPConnection to 131.169.65.104:10000 (6b927fb)
> [ClientMessageReceptor0] INFO org.jacorb.orb.iiop.ClientIIOPConnection - Client-side TCP transport to 131.169.65.104:10000 closed.
> [main] WARN org.jacorb.giop.conn - Abnormal connection termination. Lost 1 outstanding replie(s)!
> [main] INFO org.jacorb.orb.iiop.ClientIIOPConnection - Client-side TCP transport to 131.169.65.240:39478 closed.
> [main] ERROR org.tango.client.ez.proxy.DeviceProxyWrapper - DeviceProxyWrapper#executeCommand has failed.
>

Looks like jacorb randomly closes underlying connection:
> [main] WARN org.jacorb.giop.conn - Abnormal connection termination. Lost 1 outstanding replie(s)!

And if the client is so unlucky that it is awaiting a response in this moment it crashes with the timeout exception.

Reported by: Ingvord ( http://sf.net/u/ingvord )

Original Ticket: [tango-cs/bugs/710](https://sourceforge.net/p/tango-cs/bugs/710)

### PR DESCRIPTION
**Pull request by Ingvord**
Resolves #19 (?)

### CODE REVIEW

**Review by bourtemb — COMMENTED** [review]
Is getClientHostName() now returning an IP address instead of an hostname?

**Comment by Ingvord** [comment]
> Is getClientHostName() now returning an IP address instead of an hostname?

Yes. I would say if client needs hostName it should do name resolving

**Comment by bourtemb** [comment]
> > Is getClientHostName() now returning an IP address instead of an hostname?
> 
> Yes. I would say if client needs hostName it should do name resolving

I think it is expected for a method named getClientHostName() to return a hostname, not an IP address. This is why the method was doing the name resolving.
As far as I see, in JTango code, this seems to be used at least in the device blackbox, in InvocationContext.getClientHostName() and in DeviceManager.getClientHostName().
I have no clear idea about the impact on our users.
One obvious impact is that they will see the IP address of the client instead of its hostname in the blackbox results, which is not very nice for the users compared to what they are used to.
I don't know where InvocationContext.getClientHostName() and DeviceManager.getClientHostName() are used.
At first sight it looks like this pull request is downgrading in some way the user experience even though it is trying to solve something which would also improve the user experience, for the users having troubles configuring their network.
I'd be happy to hear the opinion of other users...

**Comment by Ingvord** [comment]
@bourtemb ,
 I totally agree with you about the method name etc.

But we (HZG, DESY) are users as well and our experience currently with random timeouts rather poor. I would sacrifice fancy host name in the blackbox (which we do not use BTW) in favor of not having random timeouts due to the fact that Tango makes undocumented hidden call to DNS on every client request.

Of course, I agree with you to wait for others input

**Comment by bourtemb** [comment]
As @taurel suggested to me , the right approach would be to do like in cppTango: to do the host naming resolution only when the blackbox is requested, and not every time a CORBA request is received as it seems to be the case in the current version (but maybe I didn't interpret well the current code).
I think this solution would make everybody happy.

**Comment by bourtemb** [comment]
Still I am not sure about the side effects on InvocationContext and DeviceManager classes which are also exposing a getClientHostName() method which seems to use ServerRequestInterceptor.getClientHostName()
I have no idea whether anyone is using it and in which context.

**Comment by Ingvord** [comment]
Sure, @gwen-soleil should have more insights.

**Comment by gwen-soleil** [comment]
-  For https://github.com/tango-controls/JTango/blob/14a6527e3ca67339e51a905ef6c55d773ed04cb7/server/src/main/java/org/tango/server/device/DeviceManager.java#L341-L344: these method is deprecated since a while now, maybe we should remove them? I don't think it has been really used.
- InvocationContext it used to pass the context to the equivalent of "always_executed_hook" in cppTango (with Java annotation AroundInvoke) . So if we move the name resolution to InvocationContext, it can affect also the performance of the device (in case of using @AroundInvoke).

Maybe the best solution is to add a feature toggle (with a Java system property and/or a setter in ServerManager)?

**Comment by Ingvord** [comment]
@gwen-soleil , thanks for your input

> these method is deprecated since a while now, maybe we should remove them? I don't think it has been really used.

Perfect let's remove them :) Less code to support -> less error prone

> So if we move the name resolution to InvocationContext, it can affect also the performance of the device (in case of using @AroundInvoke).

Well in this case we can document - "Do not use unless absolutely necessary". But I would prefer to remove this method at all and just provide ip in InvocationContext. If required client code will be forced to do name resolving and it will be explicit:

```java
@AroundInvoke
public void aroundInvoke(InvocationContext ctx){
  String hostName = InetAddress.getByName(ctx.getClientIPAddress()).getCanonicalHostName();
  //...
}
```

> Maybe the best solution is to add a feature toggle (with a Java system property and/or a setter in ServerManager)?

I strongly disagree - all these toggles... very quickly become an undocumented mess with tons of **if-else** statements in the code. As it is not a really wide spread feature right now the best is to push it as far away from the  core library as possible i.e. into the end-client code

**Comment by bourtemb** [comment]
>     * For https://github.com/tango-controls/JTango/blob/14a6527e3ca67339e51a905ef6c55d773ed04cb7/server/src/main/java/org/tango/server/device/DeviceManager.java#L341-L344
>       : these method is deprecated since a while now, maybe we should remove them? I don't think it has been really used.

Good!

>     * InvocationContext it used to pass the context to the equivalent of "always_executed_hook" in cppTango (with Java annotation AroundInvoke) . So if we move the name resolution to InvocationContext, it can affect also the performance of the device (in case of using @AroundInvoke).

So does this mean that some device servers may rely on that to get the client hostname information obtained from the InvocationContext?
Well, if we do the name resolution in InvocationContext.getClientHostName(), the name resolution will occur only if the device server asks for it? So it will affect the performances of the device servers requiring it, which sounds fine to me.

The solution proposed by @ingvord to provide only the IP address from InvocationContext might be good enough... unless there are really many device servers relying on that feature?

> Maybe the best solution is to add a feature toggle (with a Java system property and/or a setter in ServerManager)?

I am not convinced it is a good idea to do an host name resolution at each CORBA request in any case.
At the ESRF, we really enjoy having the hostnames in the blackbox results and we would like to keep this feature at least. But in this case, the name resolution can be done when creating the DevVarStringArray reply to the BlackBox command.

**Comment by Ingvord** [comment]
So summing up:

1) remove getClientHostName from both DeviceManager and InvocationContext. Device servers that use them won't compile - forcing users to rewrite the logic. This must be clearly indicated in the release notes

2) In black box do name resolving on demand

If agreed let s proceed

**Comment by gwen-soleil** [comment]
Hi, I found another solution that I think can comply with both needs. I have done the name resolution asynchronously, cf commit 43561ceaa397e414f589a05e30fc0fe2a8fd0eff

**Pull request closed without merging**
