### PR TITLE
enable javadoc.jar generation (PR for #73)

### PR DESCRIPTION
**Pull request by Ingvord**
Enable javadoc generation while disabling doclint

### CODE REVIEW

**Comment by bourtemb** [comment]
I think we need to use a different configuration for jdk1.7 and jdk1.8.
So we should probably use a maven profile activated only for jdk 1.8 as explained in the best answer given here:
https://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete/34809831#34809831

**Comment by Ingvord** [comment]
@bourtemb , yes we can have a maven profile. Also it is possible to just drop JDK7 - I do not think it is really used by anyone by now.

**Comment by bourtemb** [comment]
@ingvord, I talked with @Pascal-Verdier , no problem on our side to drop JDK7.
@gwen-soleil, what do you think?

**Comment by gwen-soleil** [comment]
Unfortunately, we still have to maintain java7 at SOLEIL because it is used inside our SCADA tool that still not support java 8. We have requested our supplier (https://www.ordinal.fr/en/mes-scada-software.htm) to migrate to java 8. And we hope that it can be done by the end of 2019.

**Comment by Ingvord** [comment]
I have done some homework and now it looks much better - basically sources and javadoc jars have been moved to release profile, so Travis is now happy and javadoc has been uploaded to bintray as well:

mvn_central_sync_error1

I would suggest to make a new release and sync it with maven central

**Comment by bourtemb** [comment]
> I would suggest to make a new release and sync it with maven central

Sounds good to me :-)

**Review by gwen-soleil — APPROVED** [review]

**Pull request merged**
