### PR TITLE
Backport: bind to multiple NICs

### PR DESCRIPTION
**Pull request by Ingvord**
as per [Tango kernel teleconf](https://github.com/tango-controls/tango-kernel-followup/blob/master/2018-09-14/Minutes.md#5-go-through-the-main-issues-and-define-priorities)

### CODE REVIEW

**Comment by bourtemb** [comment]
@ingvord, what is the status of this PR?
Is it ready to be reviewed (last commit starts with "Progress:")?

**Comment by bourtemb** [comment]
It looks like there are some conflicts to be resolved now...

**Comment by Ingvord** [comment]
@bourtemb , I have to check... Let's discuss tomorrow at Kernel teleconf meeting

**Comment by gwen-soleil** [comment]
Sorry, I was late at the teleconf today.
What is the priority of this issue? Is someone is blocked?
If not, we could do the merge all together at the next tango kernel meeting? Anyway, if I have to the merge by myself, my time is very limited, so any help is appreciated...

**Comment by bourtemb** [comment]
Hi @gwen-soleil ,
We are interested in getting this issue fixed because we have some event reconnection issues with some of our GUIs when we restart some device servers on some hosts having several network interfaces.
The GUIs are not operating as they should in this case and are sending read_attribute synchronous calls every 10 seconds because the heartbeat mechanism does not work as expected after a device server restart.

**Comment by bourtemb** [comment]
Ooops, it looks like our problem is not linked to this PR which is actually changing the Java Device server side.
Our problem seems to be on the client side... Sorry for the confusion...

**Pull request merged**
